// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
	"time"
)

type Querier interface {
	CreateUser(ctx context.Context, arg CreateUserParams) (time.Time, error)
	UserByEmail(ctx context.Context, email string) (User, error)
	UserByUsername(ctx context.Context, username string) (User, error)
	UserExistsByEmail(ctx context.Context, email string) (bool, error)
	UserExistsByUsername(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
