// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.14.0

package db

import (
	"context"
	"time"
)

type Querier interface {
	AddAccountBalance(ctx context.Context, arg AddAccountBalanceParams) (Accounts, error)
	CreateAccount(ctx context.Context, arg CreateAccountParams) (Accounts, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (time.Time, error)
	GetAccount(ctx context.Context, id int64) (Accounts, error)
	GetAccountForUpdate(ctx context.Context, id int64) (Accounts, error)
	ListAccounts(ctx context.Context, arg ListAccountsParams) ([]Accounts, error)
	UpdateAccount(ctx context.Context, arg UpdateAccountParams) (Accounts, error)
	userExistsByEmail(ctx context.Context, email string) (bool, error)
	userExistsByUsername(ctx context.Context, username string) (bool, error)
}

var _ Querier = (*Queries)(nil)
